### ISSUE TITLE
Warnings shown in Local by Flywheel

### ISSUE THREAD

**Issue by sistercylon** [MWDelaney/sage-advanced-custom-fields#1]
This is my first git issue, so apologies if it's not formatted correctly or is due to my use of Local for a virtual server (and the fact that it annoyingly injects the error output into the page instead of logging it). 

Local by Flywheel 2.4.5
WordPress 4.9.8
2018 MacBook Pro / OS 10.4

**This is showing at the top of each page and on the dashboard.&**
Warning: Use of undefined constant WP_ENV - assumed 'WP_ENV' (this will throw an Error in a future version of PHP) in /app/public/wp-content/themes/identafire/vendor/mwdelaney/sage-advanced-custom-fields/advanced-custom-fields.php on line 11

**This is showing on the dashboard, three times (I know this is usually caused by extra line breaks in php files)**
Cannot modify header information - headers already sent by (output started at /app/public/wp-content/themes/identafire/vendor/mwdelaney/sage-advanced-custom-fields/advanced-custom-fields.php:11) in /app/public/wp-admin/includes/misc.php on line 1126

[Screenshot Here](https://imgur.com/a/2PF5PiR)

**Comment by andreabrunato** [comment]
Got same error on a fresh Sage install: 

Warning: Use of undefined constant WP_ENV - assumed 'WP_ENV' (this will throw an Error in a future version of PHP) in /var/www/public/wp-content/themes/[sitename]/vendor/mwdelaney/sage-advanced-custom-fields/advanced-custom-fields.php on line 11

Using latest Wordpress and php7.2. with ACF 5.8 beta 3 active.

**Comment by sistercylon** [comment]
My webhost, Kinsta, upgraded to php 8.0 and now the site is broken. It gives the following error:

Fatal error: Uncaught Error: Undefined constant "App\WP_ENV" in /www/zisucade_762/public/wp-content/themes/identafire/vendor/mwdelaney/sage-advanced-custom-fields/advanced-custom-fields.php:11 Stack trace: #0 /www/zisucade_762/public/wp-content/themes/identafire/vendor/composer/autoload_real.php(66): require() #1 /www/zisucade_762/public/wp-content/themes/identafire/vendor/composer/autoload_real.php(56): composerRequire914211c3730db6e3927480df02824ab4('d28648b76004e76...', '/www/zisucade_7...') #2 /www/zisucade_762/public/wp-content/themes/identafire/vendor/autoload.php(7): ComposerAutoloaderInit914211c3730db6e3927480df02824ab4::getLoader() #3 /www/zisucade_762/public/wp-content/themes/identafire/resources/functions.php(47): require_once('/www/zisucade_7...') #4 /www/zisucade_762/public/wp-settings.php(585): include('/www/zisucade_7...') #5 /www/zisucade_762/public/wp-config.php(77): require_once('/www/zisucade_7...') #6 /www/zisucade_762/public/wp-load.php(50): require_once('/www/zisucade_7...') #7 /www/zisucade_762/public/wp-admin/admin.php(34): require_once('/www/zisucade_7...') #8 /www/zisucade_762/public/wp-admin/themes.php(10): require_once('/www/zisucade_7...') #9 {main} thrown in /www/zisucade_762/public/wp-content/themes/identafire/vendor/mwdelaney/sage-advanced-custom-fields/advanced-custom-fields.php on line 11
