### ISSUE TITLE
Custom Fields admin menu item showing on staging

### ISSUE THREAD

**Issue by stuartcusackie** [MWDelaney/sage-advanced-custom-fields#4]
I've noticed that the package hides the 'Custom Fields' menu on production but not on staging.

I generally remove it from staging too using code in filters.php but maybe there's a good reason not to? Can we get the package to do this?

**Comment by MWDelaney** [comment]
I've found that it's sometimes helpful to be able to dig around in the ACF config on staging if something is misbehaving. I plan to leave it visible on staging at the moment. You're free to fork this project and make the change yourself, though!

**Comment by stuartcusackie** [comment]
Cool. Just checking. I've ended up with ACF field sync conflicts before after syncing my database from staging, but perhaps I'm doing things the wrong way around. I'll keep thinking on it...

Thanks for the package!
