### ISSUE TITLE
Warning: mkdir(): No such file or directory

### ISSUE THREAD

**Issue by stuartcusackie** [MWDelaney/sage-advanced-custom-fields#6]
Seems to problem with v1.5 with a fresh Roots set up. On saving my first ACF group I get this error:

Warning: mkdir(): No such file or directory in /srv/www/mysite.test/current/web/app/themes/mytheme/vendor/mwdelaney/sage-advanced-custom-fields/advanced-custom-fields.php on line 34

I have downgraded to v1.4 and I see no issues there.

**Comment by jopfre** [comment]
Workaround is to create the acf-json directory manually in /resources/assets

**Comment by YarGnawh** [comment]
Maybe change https://github.com/MWDelaney/sage-advanced-custom-fields/blob/ea7e0a06f59566e4c2a16e778479fd62090a0191/advanced-custom-fields.php#L34 to `mkdir($path, 0777, true);`

**Comment by catgofire** [comment]
In the latest Sage they flattened the `resources/` directory... there is no longer a `resources/assets/` dir. Eventually this should be changed:

```php
// This is Sage 10
$path = get_stylesheet_directory() . '/resources/assets/acf-json';
```

to

```php
// This is Sage 10
$path = get_stylesheet_directory() . '/resources/acf-json';
```

**Comment by MWDelaney** [comment]
This is a great. We should probably add a conditional to check the existence of the first directory and fall back to the second. I'll take a stab at this unless someone here wants to make a PR!
